/*
█████████████████████████████████████████████
1) BU DOSYA, REACT UYGULAMASININ TARAYICIDA BAŞLADIĞI ANA ENTRY DOSYASIDIR.
2) GENEL OLARAK App BİLEŞENİNİ DOM İÇİNDEKİ KÖK ELEMANINA BAĞLAMA GÖREVİ BU DOSYAYA AİTTİR.
3) index.css GİBİ GLOBAL STİL DOSYALARI ÇOĞU ZAMAN BURADAN İTHAL EDİLİR.
4) REACT createRoot / render AKIŞI NORMALDE BU DOSYANIN TEMEL İŞLEVİDİR.
5) UYGULAMANIN TARAYICIDA İLK AÇILAN DOSYASI OLDUĞU İÇİN FRONTEND BAŞLATMA NOKTASI SAYILIR.
6) App.tsx DOSYASIYLA BİRLİKTE ÇALIŞARAK ROUTER VE SAYFALARI EKRANA BASAR.
7) VITE TABANLI PROJELERDE BU DOSYA, DERLEYİCİNİN İLK YÜKLEDİĞİ TSX GİRİŞİDİR.
8) DOSYANIN KENDİSİ KÜÇÜK OLSA DA UYGULAMANIN AYAĞA KALKMASI ONUNLA BAŞLAR.
9) BURADAKİ BİR HATA, TÜM UYGULAMANIN BOŞ EKRANLA AÇILMASINA NEDEN OLABİLİR.
10) KISACA: BU DOSYA, REACT UYGULAMASINI TARAYICIYA MONTE EDEN ANA FRONTEND BAŞLATMA DOSYASIDIR.
█████████████████████████████████████████████
*/

import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.tsx';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
